spring.application.name=soccer_booking_server

spring.datasource.url=jdbc:mysql://localhost:3306/soccer_booking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true


zalopay.appId=2554
zalopay.key1=sdngKKJmqEMzvh5QQcdD2A9XBSKUNaYn
zalopay.key2=trMrHtvjo6myautxDUiAcYsVtaeQ8nhf
zalopay.createEndpoint=https://sb-openapi.zalopay.vn/v2/create

